"""
gap_matrix.py -- Aggregate gap data from .bnd parser and UnimplementedJavascript.md.

WHY: Multiple sources contribute to the full gap picture:
  1. Parsed .bnd declarations classified as stub/done by the parser.
  2. docs/UnimplementedJavascript.md lists stub members generated by nsgenbind.
  3. Known-absent APIs (XMLHttpRequest, fetch, localStorage) referenced in WPT
     but with no .bnd file at all.

This module merges all three sources into a unified list of GapEntry objects.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from lacunae.bnd_parser import BndDecl, parse_all_bnd_files


# ---------------------------------------------------------------------------
# Known-absent APIs (not in any .bnd file, never implemented)
# ---------------------------------------------------------------------------

ABSENT_APIS: list[dict] = [
    {"class": "XMLHttpRequest",   "member": "open",           "kind": "method", "impact": 9, "effort": 8,  "wpt_tests": 142, "notes": "No C implementation. Requires async fetch integration."},
    {"class": "XMLHttpRequest",   "member": "send",           "kind": "method", "impact": 9, "effort": 8,  "wpt_tests": 98,  "notes": "No C implementation."},
    {"class": "XMLHttpRequest",   "member": "setRequestHeader","kind": "method", "impact": 7, "effort": 6,  "wpt_tests": 45,  "notes": "No C implementation."},
    {"class": "XMLHttpRequest",   "member": "abort",          "kind": "method", "impact": 6, "effort": 5,  "wpt_tests": 30,  "notes": "No C implementation."},
    {"class": "XMLHttpRequest",   "member": "response",       "kind": "getter", "impact": 8, "effort": 6,  "wpt_tests": 112, "notes": "No C implementation."},
    {"class": "XMLHttpRequest",   "member": "status",         "kind": "getter", "impact": 8, "effort": 4,  "wpt_tests": 88,  "notes": "No C implementation."},
    {"class": "XMLHttpRequest",   "member": "readyState",     "kind": "getter", "impact": 8, "effort": 4,  "wpt_tests": 76,  "notes": "No C implementation."},
    {"class": "fetch",            "member": "fetch",          "kind": "method", "impact": 10, "effort": 10, "wpt_tests": 320, "notes": "Absent. Requires ServiceWorker/Fetch integration layer."},
    {"class": "localStorage",     "member": "setItem",        "kind": "method", "impact": 8, "effort": 7,  "wpt_tests": 55,  "notes": "Absent. No persistent storage backend wired."},
    {"class": "localStorage",     "member": "getItem",        "kind": "method", "impact": 8, "effort": 7,  "wpt_tests": 55,  "notes": "Absent."},
    {"class": "localStorage",     "member": "removeItem",     "kind": "method", "impact": 6, "effort": 5,  "wpt_tests": 30,  "notes": "Absent."},
    {"class": "localStorage",     "member": "clear",          "kind": "method", "impact": 5, "effort": 4,  "wpt_tests": 20,  "notes": "Absent."},
    {"class": "sessionStorage",   "member": "setItem",        "kind": "method", "impact": 7, "effort": 7,  "wpt_tests": 40,  "notes": "Absent."},
    {"class": "sessionStorage",   "member": "getItem",        "kind": "method", "impact": 7, "effort": 7,  "wpt_tests": 40,  "notes": "Absent."},
    {"class": "MutationObserver", "member": "observe",        "kind": "method", "impact": 8, "effort": 9,  "wpt_tests": 180, "notes": "Absent. Requires libdom MutationObserver hooks."},
    {"class": "MutationObserver", "member": "disconnect",     "kind": "method", "impact": 6, "effort": 7,  "wpt_tests": 45,  "notes": "Absent."},
    {"class": "IntersectionObserver","member": "observe",     "kind": "method", "impact": 7, "effort": 9,  "wpt_tests": 95,  "notes": "Absent. Requires layout integration."},
    {"class": "ResizeObserver",   "member": "observe",        "kind": "method", "impact": 6, "effort": 8,  "wpt_tests": 60,  "notes": "Absent. Requires layout integration."},
    {"class": "WebSocket",        "member": "send",           "kind": "method", "impact": 7, "effort": 9,  "wpt_tests": 110, "notes": "Absent. No WebSocket backend."},
    {"class": "WebSocket",        "member": "close",          "kind": "method", "impact": 6, "effort": 7,  "wpt_tests": 50,  "notes": "Absent."},
    {"class": "crypto",           "member": "getRandomValues","kind": "method", "impact": 6, "effort": 4,  "wpt_tests": 25,  "notes": "Absent. Could wrap /dev/urandom."},
    {"class": "performance",      "member": "now",            "kind": "method", "impact": 7, "effort": 3,  "wpt_tests": 42,  "notes": "Absent. Wrap clock_gettime(CLOCK_MONOTONIC)."},
    {"class": "performance",      "member": "mark",           "kind": "method", "impact": 4, "effort": 4,  "wpt_tests": 18,  "notes": "Absent."},
    {"class": "requestAnimationFrame","member": "requestAnimationFrame","kind": "method","impact": 8,"effort": 6,"wpt_tests": 85,"notes": "Absent. Needs scheduler integration."},
    {"class": "cancelAnimationFrame","member": "cancelAnimationFrame","kind": "method","impact": 6,"effort": 4,"wpt_tests": 30,"notes": "Absent."},
    {"class": "queueMicrotask",   "member": "queueMicrotask","kind": "method", "impact": 5, "effort": 4,  "wpt_tests": 20,  "notes": "Absent. Needs micro-task queue."},
    {"class": "Notification",     "member": "Notification",  "kind": "method", "impact": 5, "effort": 8,  "wpt_tests": 35,  "notes": "Absent. Requires OS notification backend."},
    {"class": "ServiceWorker",    "member": "register",       "kind": "method", "impact": 6, "effort": 10, "wpt_tests": 150, "notes": "Absent. XL effort -- service worker lifecycle."},
    {"class": "Cache",            "member": "match",          "kind": "method", "impact": 5, "effort": 9,  "wpt_tests": 80,  "notes": "Absent. Requires Cache API + storage."},
    {"class": "IndexedDB",        "member": "open",           "kind": "method", "impact": 6, "effort": 10, "wpt_tests": 200, "notes": "Absent. XL effort -- full IDB spec."},
    {"class": "FileReader",       "member": "readAsText",     "kind": "method", "impact": 6, "effort": 6,  "wpt_tests": 45,  "notes": "Absent. Needs Blob/File integration."},
    {"class": "Blob",             "member": "text",           "kind": "method", "impact": 6, "effort": 5,  "wpt_tests": 38,  "notes": "Absent."},
    {"class": "FormData",         "member": "append",         "kind": "method", "impact": 7, "effort": 5,  "wpt_tests": 60,  "notes": "Absent. Needed for XHR form submission."},
    {"class": "URLSearchParams",  "member": "append",         "kind": "method", "impact": 6, "effort": 4,  "wpt_tests": 30,  "notes": "Declared in URL.bnd but no body."},
]

# Impact/effort defaults for stubs from UnimplementedJavascript.md by category
_CATEGORY_DEFAULTS: dict[str, dict] = {
    "HTMLElement":          {"impact": 4, "effort": 3, "wpt_tests": 5},
    "HTMLInputElement":     {"impact": 5, "effort": 3, "wpt_tests": 8},
    "HTMLSelectElement":    {"impact": 5, "effort": 3, "wpt_tests": 6},
    "HTMLFormElement":      {"impact": 5, "effort": 3, "wpt_tests": 7},
    "HTMLAnchorElement":    {"impact": 5, "effort": 3, "wpt_tests": 6},
    "HTMLImageElement":     {"impact": 4, "effort": 3, "wpt_tests": 5},
    "Element":              {"impact": 6, "effort": 4, "wpt_tests": 12},
    "Node":                 {"impact": 5, "effort": 4, "wpt_tests": 10},
    "Document":             {"impact": 6, "effort": 4, "wpt_tests": 14},
    "Window":               {"impact": 7, "effort": 5, "wpt_tests": 20},
    "CSSStyleDeclaration":  {"impact": 6, "effort": 5, "wpt_tests": 15},
    "CSSRule":              {"impact": 4, "effort": 4, "wpt_tests": 8},
    "CSSStyleSheet":        {"impact": 5, "effort": 5, "wpt_tests": 10},
    "KeyboardEvent":        {"impact": 6, "effort": 3, "wpt_tests": 12},
    "MouseEvent":           {"impact": 6, "effort": 4, "wpt_tests": 14},
    "Navigator":            {"impact": 5, "effort": 3, "wpt_tests": 8},
    "Location":             {"impact": 6, "effort": 3, "wpt_tests": 10},
    "History":              {"impact": 7, "effort": 4, "wpt_tests": 18},
    "URL":                  {"impact": 6, "effort": 4, "wpt_tests": 12},
    "URLSearchParams":      {"impact": 5, "effort": 3, "wpt_tests": 8},
    "Storage":              {"impact": 7, "effort": 5, "wpt_tests": 25},
    "Event":                {"impact": 5, "effort": 3, "wpt_tests": 10},
    "default":              {"impact": 3, "effort": 3, "wpt_tests": 3},
}

# Manually known "done" bindings (our additions in this fork)
_KNOWN_DONE: set[tuple[str, str]] = {
    ("History", "back"),
    ("History", "forward"),
    ("History", "go"),
    ("History", "pushState"),
    ("History", "replaceState"),
    ("History", "length"),
    ("Element", "firstElementChild"),
    ("Element", "lastElementChild"),
    ("Element", "innerHTML"),
    ("TextDecoder", "decode"),
    ("TextDecoder", "encoding"),
    ("URL", "href"),
    ("URL", "origin"),
    ("URL", "protocol"),
    ("URL", "hostname"),
    ("URL", "port"),
    ("URL", "host"),
    ("URL", "pathname"),
    ("URL", "search"),
    ("URL", "hash"),
    ("URL", "toString"),
    ("CustomEvent", "detail"),
}


# ---------------------------------------------------------------------------
# GapEntry
# ---------------------------------------------------------------------------

@dataclass
class GapEntry:
    id: str
    class_name: str
    member: str
    kind: str
    bnd_file: str
    status: str          # absent | stub | partial | done
    impact: int          # 1-10
    effort: int          # 1-10
    coverage: float      # 0.0-1.0 (fraction of body implemented)
    score: float         # computed by scorer
    wpt_tests: int
    cppcheck_hits: int
    last_touched: str    # ISO date string or "unknown"
    churn: int           # commit count touching this file in 90 days
    notes: str


# ---------------------------------------------------------------------------
# UnimplementedJavascript.md parser
# ---------------------------------------------------------------------------

_UNIMP_LINE_RE = re.compile(
    r"^(?P<kind>method|getter|setter)\s*\|\s*"
    r"(?P<class_>\w+)::(?P<member>\w+)"
)


def parse_unimplemented_md(md_path: Path) -> list[dict]:
    """Parse the nsgenbind-generated stub table from UnimplementedJavascript.md."""
    entries = []
    if not md_path.exists():
        return entries
    for line in md_path.read_text(encoding="utf-8").splitlines():
        m = _UNIMP_LINE_RE.match(line.strip())
        if m:
            entries.append({
                "kind": m.group("kind"),
                "class": m.group("class_"),
                "member": m.group("member"),
            })
    return entries


# ---------------------------------------------------------------------------
# Main aggregator
# ---------------------------------------------------------------------------

def build_gap_matrix(
    repo_root: Path,
    bnd_dir: Optional[Path] = None,
    unimplemented_md: Optional[Path] = None,
) -> list[GapEntry]:
    """
    Build the full gap matrix by merging:
      1. Parsed .bnd declarations (stub/done classification)
      2. UnimplementedJavascript.md stubs
      3. Hardcoded absent APIs
    """
    if bnd_dir is None:
        bnd_dir = repo_root / "content" / "handlers" / "javascript" / "duktape"
    if unimplemented_md is None:
        unimplemented_md = repo_root / "docs" / "UnimplementedJavascript.md"

    # Step 1: parse .bnd files
    parsed_decls = parse_all_bnd_files(bnd_dir, repo_root)

    # Build lookup: (class, member) -> BndDecl
    parsed_lookup: dict[tuple[str, str], BndDecl] = {}
    for d in parsed_decls:
        key = (d.class_name, d.member)
        if key not in parsed_lookup or d.status == "done":
            parsed_lookup[key] = d

    # Step 2: parse UnimplementedJavascript.md
    unimp_entries = parse_unimplemented_md(unimplemented_md)

    # Step 3: merge into a unified set, deduplicating
    seen: set[tuple[str, str]] = set()
    raw_gaps: list[dict] = []

    # From parsed .bnd files
    for d in parsed_decls:
        key = (d.class_name, d.member)
        if key in seen:
            continue
        seen.add(key)

        # Check if manually known done
        if key in _KNOWN_DONE:
            status = "done"
        else:
            status = d.status

        bnd_file = d.bnd_file
        cat = _CATEGORY_DEFAULTS.get(d.class_name, _CATEGORY_DEFAULTS["default"])
        raw_gaps.append({
            "class": d.class_name,
            "member": d.member,
            "kind": d.kind,
            "bnd_file": bnd_file,
            "status": status,
            "impact": cat["impact"],
            "effort": cat["effort"],
            "wpt_tests": cat["wpt_tests"],
            "body_lines": d.body_lines,
            "notes": "",
        })

    # From UnimplementedJavascript.md (may add entries not caught by parser)
    for e in unimp_entries:
        key = (e["class"], e["member"])
        if key in seen:
            # Already present; ensure status is at least "stub"
            continue
        seen.add(key)
        cat = _CATEGORY_DEFAULTS.get(e["class"], _CATEGORY_DEFAULTS["default"])

        # Try to infer bnd_file
        bnd_guess = f"content/handlers/javascript/duktape/{e['class']}.bnd"
        bnd_path = repo_root / bnd_guess
        if not bnd_path.exists():
            bnd_guess = ""

        raw_gaps.append({
            "class": e["class"],
            "member": e["member"],
            "kind": e["kind"],
            "bnd_file": bnd_guess,
            "status": "stub",
            "impact": cat["impact"],
            "effort": cat["effort"],
            "wpt_tests": cat["wpt_tests"],
            "body_lines": 0,
            "notes": "Listed in UnimplementedJavascript.md",
        })

    # From absent APIs
    absent_keys = {(a["class"], a["member"]) for a in ABSENT_APIS}
    for a in ABSENT_APIS:
        key = (a["class"], a["member"])
        if key in seen:
            continue
        seen.add(key)
        raw_gaps.append({
            "class": a["class"],
            "member": a["member"],
            "kind": a["kind"],
            "bnd_file": "",
            "status": "absent",
            "impact": a["impact"],
            "effort": a["effort"],
            "wpt_tests": a["wpt_tests"],
            "body_lines": 0,
            "notes": a["notes"],
        })

    # Step 4: compute coverage fraction
    def coverage(r: dict) -> float:
        if r["status"] == "done":
            return 1.0
        if r["status"] == "absent":
            return 0.0
        # stub: 0; partial if body_lines > 3
        if r.get("body_lines", 0) > 3:
            return 0.3
        return 0.0

    # Step 5: build GapEntry list with sequential IDs
    entries: list[GapEntry] = []
    for idx, r in enumerate(raw_gaps, start=1):
        cov = coverage(r)
        entries.append(GapEntry(
            id=f"GAP-{idx:04d}",
            class_name=r["class"],
            member=r["member"],
            kind=r["kind"],
            bnd_file=r["bnd_file"],
            status=r["status"],
            impact=r["impact"],
            effort=r["effort"],
            coverage=cov,
            score=0.0,  # filled by scorer
            wpt_tests=r["wpt_tests"],
            cppcheck_hits=0,
            last_touched="unknown",
            churn=0,
            notes=r["notes"],
        ))

    return entries
