"""
graph.py -- networkx + graphviz binding dependency graph.

WHY: A visual dependency graph makes it immediately clear which gaps are
     "upstream" (blocking others) and which are leaf nodes. Color coding
     by status turns the graph into an implementation roadmap.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

try:
    import networkx as nx
    _NX_AVAILABLE = True
except ImportError:
    _NX_AVAILABLE = False

try:
    import graphviz as gv
    _GV_AVAILABLE = True
except ImportError:
    _GV_AVAILABLE = False

from lacunae.cross_ref import build_cross_ref
from lacunae.gap_matrix import GapEntry


_STATUS_COLOR = {
    "absent":  "#ff6b6b",   # red
    "stub":    "#ffd93d",   # yellow
    "partial": "#6bcfff",   # cyan
    "done":    "#6bcb77",   # green
    "unknown": "#cccccc",   # grey
}


def _class_status(class_name: str, entries: list[GapEntry]) -> str:
    """Aggregate status for a class: worst across all its members."""
    class_entries = [e for e in entries if e.class_name == class_name]
    if not class_entries:
        return "unknown"
    if any(e.status == "absent" for e in class_entries):
        return "absent"
    if any(e.status == "stub" for e in class_entries):
        return "stub"
    if any(e.status == "partial" for e in class_entries):
        return "partial"
    return "done"


def render_graph(
    repo_root: Path,
    entries: list[GapEntry],
    out_path: Optional[Path] = None,
    fmt: str = "svg",
) -> Path:
    """
    Render a binding dependency graph. Returns the output file path.
    Falls back to a DOT-format text file if graphviz Python library is absent.
    """
    if out_path is None:
        out_path = repo_root / "lacunae-report" / f"binding-graph.{fmt}"

    out_path.parent.mkdir(parents=True, exist_ok=True)

    bnd_dir = repo_root / "content" / "handlers" / "javascript" / "duktape"
    refs = build_cross_ref(bnd_dir)

    # Collect all class names from entries + refs
    all_classes: set[str] = {e.class_name for e in entries}
    for cls, deps in refs.items():
        all_classes.add(cls)
        all_classes.update(deps)

    if _GV_AVAILABLE:
        return _render_graphviz(out_path, fmt, all_classes, refs, entries)
    else:
        return _render_dot_fallback(out_path, all_classes, refs, entries)


def _render_graphviz(out_path: Path, fmt: str, all_classes: set[str],
                     refs: dict[str, set[str]], entries: list[GapEntry]) -> Path:
    dot = gv.Digraph(
        name="NetSurf JS Bindings",
        comment="Generated by lacunae",
        format=fmt,
    )
    dot.attr(rankdir="LR", fontname="monospace", bgcolor="white")
    dot.attr("node", shape="box", style="filled", fontname="monospace", fontsize="9")

    for cls in sorted(all_classes):
        status = _class_status(cls, entries)
        color = _STATUS_COLOR.get(status, _STATUS_COLOR["unknown"])
        dot.node(cls, cls, fillcolor=color)

    for cls, deps in refs.items():
        for dep in deps:
            if dep in all_classes:
                dot.edge(cls, dep)

    # Render to file (graphviz library writes source + renders)
    dot_src = dot.source
    src_path = out_path.with_suffix(".dot")
    src_path.write_text(dot_src, encoding="utf-8")

    try:
        dot.render(filename=str(out_path.with_suffix("")), cleanup=True)
    except Exception:
        pass  # dot binary may not be in PATH; .dot file is still useful

    return out_path


def _render_dot_fallback(out_path: Path, all_classes: set[str],
                         refs: dict[str, set[str]], entries: list[GapEntry]) -> Path:
    """Write a raw DOT file when graphviz Python package is unavailable."""
    lines = ['digraph "NetSurf JS Bindings" {', '  rankdir=LR;']
    for cls in sorted(all_classes):
        status = _class_status(cls, entries)
        color = _STATUS_COLOR.get(status, _STATUS_COLOR["unknown"])
        lines.append(f'  "{cls}" [fillcolor="{color}" style=filled shape=box];')
    for cls, deps in refs.items():
        for dep in sorted(deps):
            if dep in all_classes:
                lines.append(f'  "{cls}" -> "{dep}";')
    lines.append("}")
    dot_path = out_path.with_suffix(".dot")
    dot_path.write_text("\n".join(lines), encoding="utf-8")
    return dot_path
